### ISSUE TITLE
Admin dashboard is not responsive

### ISSUE THREAD

**Issue by debasishbanerjee** [krishnandusarkar/Regular.li#121]
Section : AdminMobile ->dashboard
Test case: Dashboard is not responsive.See Web Checkin table & user login/logout trail.Refer screenshot
![screenshot](https://cloud.githubusercontent.com/assets/16253897/13143638/504ef402-d66b-11e5-8212-2d9d21e99cef.png)

**Comment by snowbreeze** [comment]
tab specific issue..lowering priority
