### ISSUE TITLE
Date Field Validation

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/Regular.li#13]
Noticed that Mandatory Field validation is not working on Date Field throughout the app. E.g. Holiday, Leave Application etc. 

Date Fields should display "This field is mandatory" message in red as like other text fields.

Please let me know if there's any technical challenge.

**Comment by trijitdey** [comment]
Issues Solved

**Comment by krishnandusarkar** [comment]
Retested and working fine.
