### ISSUE TITLE
Dashboard Showing Add User

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#136]
Problem Summary: Admin dashboard showing add user, even if user is added
Steps to Reproduce: Create company, add user, login to dashboard as admin, Username-avijit@regular.li & Password- password12
Expected Result: if users are added, it should not say add user
Actual Result: it is saying add user
Platform: android, ios
Version: android- 20 , ios- 3.0

![img_5042](https://cloud.githubusercontent.com/assets/19668188/15676521/2534199c-2764-11e6-8d00-69628a73becc.PNG)

**Comment by snowbreeze** [comment]
Done check
