### ISSUE TITLE
Dashboard Admins getting hanged

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#137]
Problem Summary: Admin dashboard admins getting hanged
Steps to Reproduce: Create company, login to dashboard as admin, go to menu then click Admins
Expected Result: Admin dashboard should show on 
Actual Result: It is getting hanged
Platform: android, ios
Version: android- 20, ios-3.0

![aqua_y2_1gb_screenshot_20160601_115039](https://cloud.githubusercontent.com/assets/19668188/15700174/0fe6f622-27f0-11e6-852e-23ada629ddcd.png)

**Comment by snowbreeze** [comment]
Done check
