### ISSUE TITLE
Notification on phone

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#138]
Problem to summary: Getting notification on phone "Its time to check in!"
Expected Result: If users are already check in, then it should not send notification
Actual Result: Its send notification even if users are already check in
Platform: android
Version: android-20

![aqua_y2_1gb_screenshot_20160601_122603](https://cloud.githubusercontent.com/assets/19668188/15701053/78a73bfe-27f5-11e6-926d-cfd5411ac186.png)

**Comment by snowbreeze** [comment]
Test
