### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#139]
Problem to Summary: Admin Reports showing wrong reports
Step to Reproduce: Open Mobile App, Login to dashboard as admin, go to menu then click reports
Expected Result: Users Present
Actual Result: Days Present
Platform: Android, Ios, Web
Version: Android- 20, Ios- 3.0

![aqua_y2_1gb_screenshot_20160601_170228](https://cloud.githubusercontent.com/assets/19668188/15708190/c52ac976-281a-11e6-8d58-fcc763b75c30.png)

**Comment by snowbreeze** [comment]
Done check on next release

**Comment by trijitdey** [comment]
Changed to present count
