### ISSUE TITLE
Form Loader Issue

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/Regular.li#14]
On all forms, if you do not type anything and just click submit, it shows the required validation message which is fine, but the loader keeps showing.

Loader should only be shown when some background operations is going on and the screen should be disabled for further operations

![screenshot_2015-12-02-23-14-05](https://cloud.githubusercontent.com/assets/3623328/11539034/fbf9770e-994a-11e5-8ea9-5c7a58341148.png)

**Comment by trijitdey** [comment]
issue solved.
