### ISSUE TITLE
Admin Dashboard Showing total 4 users 

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#141]
Problem to Summary: When login to admin dashboard it is showing total 4 users, but actually 5 users were present.                       
Step to Reproduce: Open Mobile App, Login to dashboard as admin (Username- avijit@regular.li & Password- password12 )
Expected Result: When 5 users were checkin then total users will be shown 5
Actual Result: Total users are 4 & present users are 5 
Platform: Android, Ios, Web
Version: Android- 20, Ios- 3.0

![img_5070](https://cloud.githubusercontent.com/assets/19668188/15779522/7e8c6e4c-29ba-11e6-8a64-478af0238b2b.PNG)

**Comment by snowbreeze** [comment]
because admin has not confirmed email.
@krishnandusarkar should we increase the admin count even if admin doesnt confirm email? as all other functions are working without confirmation. This is the api for count
"/api/Account/UserCount"

**Comment by snowbreeze** [comment]
@moutusi12singh Please check and Close ussue
