### ISSUE TITLE
company settings must override user setting

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#146]
Problem summary: company geoseal is disabled, user geoseal enabled & yet while checkin it is showing location is mandatory 
Step to reproduce: enable geoseal in user & disable geoseal in company & try to checkin from away
Expected: it should allow checkin
Actual: it is saying location mandatory
Platform: Ios, Android
Version: 4.0, 22

**Comment by krishnandusarkar** [comment]
Hierarchically the lower node should be prioritized.

On New User (While Creating) : Use the settings from company level.

For all other cases (i.e. existing users) : Use the data from User

**Comment by snowbreeze** [comment]
Making it more simpler.

Add User - Show all the options. Enable those that are enabled in the company
Edit User - Show all the options. Enable those that are enabled int the user

**Comment by trijitdey** [comment]
@krishnandusarkar  Please keep it this way

If company is enabled then user may or may not be enabled.
If company is disabled then user cannot be enabled, even if he has the flag enabled

Follow this logic 
```
 var cameraRequired =  company.RestrictByPicture  &&  user.RestrictByPicture 
 var locationRequired =  company.RestrictByLocation &&  user.RestrictByLocation 
 var wifiRequired = !(typeof company.WiFiSSID == "undefined" || company.WiFiSSID == "") && user.RestrictByWiFiSSID
   ```

**Comment by krishnandusarkar** [comment]
Done. Please Test.

**Comment by krishnandusarkar** [comment]
@moutusi12singh Please Test
