### ISSUE TITLE
Dashboard getting hanged

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#150]
Problem Summary:  dashboard getting hanged
Steps to Reproduce: Create company, login to dashboard as admin, go to menu then click Dashboard
Expected Result:  Dashboard should show on 
Actual Result: It is getting hanged
Platform: android
Version: 22

![aqua_y2_1gb_screenshot_20160614_141501](https://cloud.githubusercontent.com/assets/19668188/16036849/52cf347c-323b-11e6-8a0b-f882fd6dc92b.png)

**Comment by snowbreeze** [comment]
@trijit include the network level error messages in this


*Avijit Sarkar*
CEO

+91 7278027780
steve@avifainfotech.com

Avifa Infotech Pvt Ltd



http://www.avifainfotech.com

Skype:snowbreez
Personal Profile: http://www.avijitsarkar.com
