### ISSUE TITLE
AttendanceByCompany URL Showing Error

### ISSUE THREAD

**Issue by trijitdey** [krishnandusarkar/Regular.li#151]
GET Url : http://regularly.azurewebsites.net/api/AttendanceByCompany?dateFrom=2016-06-07&dateTo=2016-06-14

TOKEN : bearer O3TjRotnRYQs8Ko-baw3VJxQgSMfXBTohI_sAEP-mIWgdZ5h1ot4xA1YktjJoOipwGHUYOIFydBZN8eRfnvKpZfVuDGQk6_sG04GSEGwTw4YzH-XSwXg4iJwqrau1_YLjqaYMXQr4uuLbqwwTn9vPAWZ2JL2MjGB9O-kniDMJtOUDpAhLXlsKqJOC7UKtQHrabkXAX69my_d6jXyl0CZDJi0Re1W2h1aStVqw7I_cmSHKoOoNAQDN3ykUSHSgADMkGYo9SJqqVabzMPGpdzIy0vrNES0gDEsf88ikQItqhF48Ulyg3NWsrxz_A-EG1M69m4wYzINfC7eKpE9Uhyk59bZbTTsrOttcFPxgqtEch7e9DKFZDJuQIdVOcj9S7lWLglvh-cWOCSGHWn666yBSscv_n0uhPL8jvSbyRhzds3mWpTCP8Rf_jleVBU3FBgXDa75IaZzVWVFNyIhr28vz1ZIUbKEfPmqlP-xgkOEslYO_-3y8U4ZMC3avyxENO3hiloPjqC2S7YSKLf234E_08MaF518FFnfrdQpsnjQQ544oKvP8FZs-R2fkxK_gazB_rh9_xbPZg0CJ6sDtDwI61uqjgAKDby_L--XIccVVpM77DjkEjbpDlkdsc3zgPUsRRWzIf-TuhWV-qm9R3kuLFCyhoifkhD2JSkRALl8YdvbUwjSdAz9EmkEWMPG5L3Rxn3BZEbyzXhGKayKH49HF3fe1kv995HKU8r5tCyOH4-AYOvKn--LONg5NhlDib7jnbCr3vZA9ENbhhIp6ODri1VmEJNkmLRPCaS7HakXONM

Getting Error Message

{
  "Message": "An error has occurred.",
  "ExceptionMessage": "The cast to value type 'System.Boolean' failed because the materialized value is null. Either the result type's generic parameter or the query must use a nullable type.",
  "ExceptionType": "System.InvalidOperationException",
  "StackTrace": "   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper.ErrorHandlingValueReader`1.GetValue(DbDataReader reader, Int32 ordinal)\r\n   at lambda_method(Closure , Shaper )\r\n   at System.Data.Entity.Core.Common.Internal.Materialization.Coordinator`1.ReadNextElement(Shaper shaper)\r\n   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()\r\n   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()\r\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at Avifa.Regularly.WebAPI.Controllers.AttendancesController.GetAttendanceByCompany(DateTime dateFrom, DateTime dateTo)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}

**Comment by krishnandusarkar** [comment]
Issue Fixed. Please test.
