### ISSUE TITLE
Dashboard Menu

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#153]
Problem Summary: If total users are 5 & when 4 users are present then the users circle will show 4/5 th grid of the circle
Step to Reproduce:  Open mobile app, then login to admin dashboard, then click dashboard
Expected: shows 4/5th grid of the circle
Actual: shows full grid of circle
Platform: Android, iOS
Version: 22, 4.0

![img_4097](https://cloud.githubusercontent.com/assets/19668188/16150331/2e2fd79a-34b4-11e6-9fb8-ad08be3a1312.jpg)

**Comment by snowbreeze** [comment]
Is this fixed?

**Comment by moutusi12singh** [comment]
not solved, same issue found.

**Comment by moutusi12singh** [comment]
fixed
