### ISSUE TITLE
Can't apply leave

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#154]
Problem Summary: when user applied for leave request, it can't send to admin.
Step to Reproduce: open mobile app, then login to user dashboard (email- moutusi@regular.li, password- moutusi21singh), then click leaves
Expected: Leave request send to admin
Actual: Leave request can't send to admin, showing error message
Platform: Android
Version: 25

![aqua_y2_1gb_screenshot_20160622_125833](https://cloud.githubusercontent.com/assets/19668188/16257978/3a2b2c48-3879-11e6-83c3-0b1492703f0a.png)

**Comment by moutusi12singh** [comment]
it is working. user can apply for leave.

**Comment by snowbreeze** [comment]
Is it working? Please close. Test in live
