### ISSUE TITLE
user can't change company

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#155]
Problem Summary: when user is already added with one company, then when new company is adding the existing user of another company & send mail to user.
Step to Reproduce: open mobile app, create new company then go to users & add the existing user of another company.
Expected: mail send on user's email id
Actual: no mail send on users email id, it shows message i.e. this email id is already taken
Platform: Android
Version: 25

![aqua_y2_1gb_screenshot_20160622_133859](https://cloud.githubusercontent.com/assets/19668188/16259121/cbe82f14-387e-11e6-8b37-f5bef1543af8.png)

**Comment by moutusi12singh** [comment]
it is not working, same message is showing.

**Comment by snowbreeze** [comment]
Is this fixed? Test on production

**Comment by moutusi12singh** [comment]
This issue is related to version- 29 on Android & iOS
