### ISSUE TITLE
Intime button not working

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#159]
Problem Summary;- Intime button not working & need some top padding.
Platform:- Android, iOS

![aqua_y2_1gb_screenshot_20160718_163600](https://cloud.githubusercontent.com/assets/19668188/16914063/d5e10b56-4d0c-11e6-86b2-f6ef4c60677d.png)

**Comment by snowbreeze** [comment]
done check

**Comment by moutusi12singh** [comment]
fixed.
