### ISSUE TITLE
Map is not showing

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#160]
Problem Summary:- Map is not showing.
Platform:- Android, iOS

![aqua_y2_1gb_screenshot_20160718_163734](https://cloud.githubusercontent.com/assets/19668188/16914106/327bc7ca-4d0d-11e6-8313-f0c0c9ef2a53.png)

**Comment by snowbreeze** [comment]
done

**Comment by moutusi12singh** [comment]
fixed.
