### ISSUE TITLE
After checkin Detect Location text disappeared

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#161]
Problem summary:- After checkin Detect Location text disappeared.
Platform:- Android, iOS

![aqua_y2_1gb_screenshot_20160718_164924](https://cloud.githubusercontent.com/assets/19668188/16914121/5742ee12-4d0d-11e6-85c8-531d718b0fe2.png)

**Comment by snowbreeze** [comment]
fixed
