### ISSUE TITLE
In Trijit Da's phone holiday & leave application showing 2 times

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#163]
Problem Summary:- In Trijit Da's phone holiday & leave application showing 2 times.

![screenshot_2016-07-18-16-56-07](https://cloud.githubusercontent.com/assets/19668188/16914179/c2206f20-4d0d-11e6-96d0-3a590d6bb588.png)

**Comment by snowbreeze** [comment]
You didnt post the login  info. Inadequate steps to reproduce.
