### ISSUE TITLE
Admin Settings Location is not working properly

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#164]
Problem Summary:- Admin Settings Location is not working properly (onclick issue) & Map is not showing.
Platform:- Android, iOS

![aqua_y2_1gb_screenshot_20160718_173552](https://cloud.githubusercontent.com/assets/19668188/16914390/29992150-4d0f-11e6-9081-cad736914cbe.png)

**Comment by snowbreeze** [comment]
chk again

**Comment by moutusi12singh** [comment]
fixed.
