### ISSUE TITLE
on time popup

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#167]
Problem Summary:- Ontime Popup
Step to Reproduce:- open mobile app, login to dashboard as user then click checkin
Expected Result:- click ok button then it will be vanish
Actual Result:- popup should automatic vanish
Platform:- Android
Version:- 29

**Comment by snowbreeze** [comment]
This is WAE

**Comment by moutusi12singh** [comment]
fixed.
