### ISSUE TITLE
user delete without active

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#168]
Problem Summary: User delete without active
Step to Reproduce: open mobile app, login to dashboard as admin, go to menu then add user & then without confirm email delete this user.
Expected Result: user not deleted without active
Actual Result: user deleted without active
Platform: Android, iOS

![aqua_y2_1gb_screenshot_20160807_141559](https://cloud.githubusercontent.com/assets/19668188/17461423/9f8ed13a-5ca9-11e6-9b53-c6a459e92819.png)

**Comment by snowbreeze** [comment]
This is WAE (Working As Expected)

**Comment by moutusi12singh** [comment]
same issue found.

**Comment by snowbreeze** [comment]
This is fine. Not an issue. Users can be deleted even if they are not active. But test this.

Suppose I add a user, user gets email, doesnt confirm, then i delete the user, then user clicks confirm, what happens now

**Comment by moutusi12singh** [comment]
At that time confirm button is not working & user is not added.
