### ISSUE TITLE
Admin checkout

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#169]
Problem Summary:- Admin Checkout
Step to Reproduce:- open mobile app, login to dashboard as admin, then click checkout
Expected Result:-  it should not stop 
Actual Result:- it should stop for some seconds then checkout 
Platform:- Android
Version: 29

**Comment by snowbreeze** [comment]
cant reproduce

**Comment by moutusi12singh** [comment]
fixed.
