### ISSUE TITLE
Notes Popup

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#170]
Problem Summary:- Notes Popup should show on general user
Step to Reproduce:- open moble app, login to admin dashboard , go to menu then add user & then field tracking button is disabled.
Expected Result:- didn't show notes popup on general user checkout
Actual Result:- show notes popup on general user checkout 
Platform:- Android, iOS
Version:- 29, 9.0

**Comment by snowbreeze** [comment]
fixed. good catch

**Comment by moutusi12singh** [comment]
same issue found

**Comment by moutusi12singh** [comment]
fixed.
