### ISSUE TITLE
Notes Popup text box (text ) color should must be changed

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#171]
Problem Summary:- Notes Popup text box (text ) color should must be changed
Step to Reproduce:- Notes Popup
Expected Result:- text should be visible
Actual Result:- text should not be visible
Platform:- Android
version:- 29

**Comment by snowbreeze** [comment]
not possible as of now

**Comment by moutusi12singh** [comment]
fixed.
