### ISSUE TITLE
Notes Popup

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#172]
Problem Summary:- Notes Popup text box (text ) color should must be changed
Step to Reproduce:- Notes Popup
Expected Result:-"This visit is nice" written in placeholder
Actual Result:- "This visit is nice" written in text format
Platform:- iOS
version:- 9.0

**Comment by snowbreeze** [comment]
fixed check

**Comment by moutusi12singh** [comment]
not fixed.

**Comment by moutusi12singh** [comment]
fixed.
