### ISSUE TITLE
Reports map is not showing correct reports

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#173]
Problem Summary:- Reports map is not showing correct reports
Step to Reproduce:- open mobile app, login to admin dashboard, go to menu then click Reports
Expected Result:- shows all pointer & correct reports on reports section
Actual Result:- It didn't show all pointer & correct report
Platform:- Android
Version:- 29

**Comment by snowbreeze** [comment]
because they are probably on the same point

**Comment by moutusi12singh** [comment]
fixed.
