### ISSUE TITLE
Existing user can't change company

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#184]
Problem Summary:- Existing user can't change present company to new company
Step to Reproduce:- Create a company, go to menu &  click User then add existng user of another comapny 
Expected Result:- mail sent to user (Asked to join)
Actual Result:- mail not send & show popup
Platform:- Android, iOS

![img_4145 1](https://cloud.githubusercontent.com/assets/19668188/18005715/546f9058-6bb9-11e6-8f37-661254a61854.PNG)

**Comment by krishnandusarkar** [comment]
Is this feature was running untested till date? There's this issue from the beginning.

Anyway fixed it and uploaded to Staging. Please test and close and let me know will then push it to Prod.

**Comment by moutusi12singh** [comment]
fixed.
