### ISSUE TITLE
user not deleted

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#186]
Problem Summary:- User not deleted in old company when they added by new company
Step to Reproduce:- open mobile app, goto menu then click user & add existing user of another company then check user section of both company old & new.
Expected Result:- User deleted in old company
Actual Result:- User show on old & new company both
Platform:- Android

**Comment by krishnandusarkar** [comment]
Cannot reproduce. Please test again

Admin1 : um1@grr.la / password12
Admin2 : un2@grr.la / password12

User : u1@grr.la / password12

Steps followed:
1. Created Admin1 and Confirmed Email
2. Created Admin2 and Confirmed Email
3. Added User to Admin2 and Confirmed Email
4. Logged In to Admin1
6. Added User to Admin1
7. User didn't showed up under Admin1 until the user confirmed the email (which is correct)
8. After user confirmed the email, it showed up under Admin1 and not showing anymore under Admin2

**Comment by moutusi12singh** [comment]
fixed.
