### ISSUE TITLE
Shows Error

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#189]
Problem Summary:- Sometimes when user click on confirm button (Acknowledge Company Change Request). A new page is open & show error.

![error](https://cloud.githubusercontent.com/assets/19668188/18865022/b9389870-84b6-11e6-8531-c12d18a25009.jpg)

**Comment by snowbreeze** [comment]
When adding an user from another company sometimes this is occuring

**Comment by krishnandusarkar** [comment]
@snowbreeze @moutusi12singh Is this happening for specific case when the user / admin is the last one in the company? Any idea?

**Comment by moutusi12singh** [comment]
No user / admin is not last one.

**Comment by moutusi12singh** [comment]
same issue found when click to confim button.

**Comment by snowbreeze** [comment]
@moutusi12singh incomplete issue, no information is available.

**Comment by moutusi12singh** [comment]
fixed.
