### ISSUE TITLE
LOVE US? RATE button is not working

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#190]
Problem Summary:- LOVE US? RATE button is not working, shows error.
Step to Reproduce:- Login to dashboard as admin (in web version), then go to menu & click Help.
Expected Result:- when click on rate button it shows a popup then click ok, then its go to rate app page.
Actual Result:- It still stay in same page and show error.
![r](https://cloud.githubusercontent.com/assets/19668188/19617632/587bbfd4-9853-11e6-842e-1ea1ed81e4ba.png)
![r1](https://cloud.githubusercontent.com/assets/19668188/19617637/7ae7b41a-9853-11e6-91eb-c5606255cb38.png)

**Comment by snowbreeze** [comment]
@trijitdey if platform is browser we need to handle these differently
