### ISSUE TITLE
Web Checkin Image Problem

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#191]
Problem Summary:- Web checkin image is not showing in Admin Dashboard when admin accept the web checkin.
Step to Reproduce:- Open app & login to dashboard as admin
Expected Result:- Image shown in dashboard.
Actual Result:- Image is not showing in dashboard, image part is blank.

**Comment by snowbreeze** [comment]
When the webcheckin is accepted, the checkin shows but the image doesnt from AttendanceByCompany

**Comment by krishnandusarkar** [comment]
@snowbreeze @trijitdey This is because from mobile end you are not sending the ImageUrl in payload. Let me know if it's otherwise

**Comment by snowbreeze** [comment]
correct
