### ISSUE TITLE
User dashboard Image Problem

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#192]
Problem Summary: In user dashboard checkin/ check out image is not showing, means image is showing like user "Photo ID" is off. 
Step to Reproduce: Open app & login to dashboard as User.
Expected Result: Proper image is showing when PhotoID is on
Actual Result: Image is not showing.

**Comment by snowbreeze** [comment]
Is it still there? Put screenshots

**Comment by moutusi12singh** [comment]
No, it is not there.
Fixed.
