### ISSUE TITLE
Clicking Issue on Export & Resend Verification Email Button

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#193]
Problem Summary: When clicking on Export & Resend Verification Email Button again and again it
Step to Reproduce: For Export-  Open app, go to menu then click Report &
                                For Resend Verification Email- Open app, go to menu then click User.
Expected Result: Until one email is not sent to email id, until then another email should not sent. And after a single click button should be disabled.
Actual Result:- Button is not disabled & click again and again.

**Comment by snowbreeze** [comment]
When clicking on Export & Resend Verification Email Button again and again it -> It what????
