### ISSUE TITLE
Automatically User Vanish

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#195]
# During, testing I have faced a problem i.e. -

1> When I tested all thing & again create another company and add two users.
2> Then again login to 1st company and add only one user from 2nd company.
3> Acknowledgement Request send to user email address & I confirmed.
4> Then I login to 2nd company to see that Company change user stay here or not.
5> Then I found that user is not here as per our expectation.
6> But I found some another thing i.e. 2nd user is also vanish (how its possible without any confirmation or without adding to another company).

**Comment by snowbreeze** [comment]
@moutusi12singh incomplete issue, assignee not set, information missing

**Comment by moutusi12singh** [comment]
fixed.
