### ISSUE TITLE
Wrong User Report

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#196]
Problem Summary:- User report showing wrong report.
Step to Reproduce:- login to user dashboard, go to menu & click Reports, then click Export
Expected Report:- showing correct reports
Actual Report:- Punctual  report is showing wrong

![user report](https://cloud.githubusercontent.com/assets/19668188/19643133/53c5e906-9a06-11e6-9255-8c8b0f0d658c.png)

**Comment by snowbreeze** [comment]
Explain wrong

**Comment by moutusi12singh** [comment]
fixed.
