### ISSUE TITLE
Enterprise issue

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#197]
Problem Summary:- when total users= 9, total present users= 5, then how ontime shows 12 users are       ontime.  
Step to Reproduce:- Login to enterprise using this username & password (username= nafisa@grr.la & password=password12)

![enter](https://cloud.githubusercontent.com/assets/19668188/19889910/b24eb32e-a05d-11e6-832c-eca022ee9570.png)

**Comment by krishnandusarkar** [comment]
Fixed in staging. Please retest.
