### ISSUE TITLE
Wrong Punctual calculation

### ISSUE THREAD

**Issue by snowbreeze** [krishnandusarkar/Regular.li#199]
**ISSUE**
Punctual is getting calculated from the last seen time, it should be calculated from the first time. 

**API**
https://regularly.azurewebsites.net/api/AttendanceByCompany?dateFrom=2016-11-09&dateTo=2016-11-16

**TOKEN**
Authorization	bearer Jkhv21w0lZIrrYiw0zwwu2E6eKQD8mDsY5bKesq_u1P7KQSkXwkiy7aAJ0dcju34dJlb1-IFIMvCRwQT5kCdKpT53TOKxvMp3pVWMl73AoULtnYXTJB0dm1xerXrKEtQvaTk9BZ0h0shXED_5c2gZHehSmfi6fB85hlLEzjhVbS1ut7VBpV5hGKQ4Ylgy6Cn4nfqRZKbz0yGibddLMIkQnZESGJYmV6nHPir2-4KjSfdOlXNtl8LFKqn2RUDuqBYxvKxrE_Zz_rquDKoVNlkktS7Rv1NEtQoyWUNsLBdSRcDZZL3xa7YpSht_ZeZtE0ejbUe0XT3kdUaUv8BTVUGopCxOSBirK4TFAZxbgcG-kAEIiW7LKSHw-Vs0PP5-rNDknaiabz0Xw1GFq5-uXn6iHpVhO_MgZOVEdV2i-1wjdHyk4bStFHaCyawyhTiQnNG1xUw59UWmmLJMpc3UIfSOz7Zs3FjO45MBx6liELfMizQEpAKBm3b72j-0z9SmWqIWjXYul5GSAqF0xuXURRYE1lYpc0ACv47WoPsHC1F4FGaKUcYPVK1oyQgsyxzu4o6WU4c3oatTywLPkbGGrRonWxj5X3lJwjZmd4NNdf20r-dmbj1R11DLp1ZtXXzqm87XNFsqHKfUlrDxzL4WqYc97ag1WBzz3u95nrfKy7QwMITSjOZJ3vSkFTpkEj6AwybQpKDe8AMuhWIn56O4fSS4GkqgNOdqvnL83Vd3WDT5w7wZfaWxpO4n7gUabl2rohw56BuIc9Tc1zCyzB-oGm4JbBwl_Audl7w4Adx9zOtr3aZBkksfWSQt_9m2SSEjR5yjztawOEQtetTK6q2KuTElsKz2DwW1aaZMmBpHqBX7sZMJmlt-gOuwIyLL501vGXX

**RESPONSE**

[
  {
    "EmpID": "33fb50b7-d92c-44c1-b958-139f76bed4de",
    "FirstName": "Moutusi",
    "LastName": "Singh",
    "InTime": "2016-11-09T11:06:15.04",
    "OutTime": "2016-11-09T18:57:30.14",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/31044af9-fd89-4857-a1e9-a25f66b7952e",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "07:51"
  },
  {
    "EmpID": "54f2827d-aae0-4489-8218-530098af3c80",
    "FirstName": "Trijit",
    "LastName": "Dey",
    "InTime": "2016-11-09T11:11:14.683",
    "OutTime": "2016-11-09T18:58:06.697",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/8033d20b-64f2-412b-8ed3-57e37d3e107d",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "07:46"
  },
  {
    "EmpID": "9ef3626c-665d-4060-8e75-608ed9b1e274",
    "FirstName": "Debasish",
    "LastName": "Banerjee",
    "InTime": "2016-11-09T11:07:22.057",
    "OutTime": "2016-11-09T11:07:22.057",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/d3d9c771-a425-4451-934b-7ab1a1f356b8",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "00:00"
  },
  {
    "EmpID": "33fb50b7-d92c-44c1-b958-139f76bed4de",
    "FirstName": "Moutusi",
    "LastName": "Singh",
    "InTime": "2016-11-10T11:02:39.003",
    "OutTime": "2016-11-10T18:56:46.453",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/7055ef0a-6db1-4fc5-9018-cebef9a8e5fa",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "07:54"
  },
  {
    "EmpID": "54f2827d-aae0-4489-8218-530098af3c80",
    "FirstName": "Trijit",
    "LastName": "Dey",
    "InTime": "2016-11-10T10:50:18.497",
    "OutTime": "2016-11-10T18:56:39.877",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/0a946351-5d8b-4781-9159-938865108a2e",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "08:06"
  },
  {
    "EmpID": "9ef3626c-665d-4060-8e75-608ed9b1e274",
    "FirstName": "Debasish",
    "LastName": "Banerjee",
    "InTime": "2016-11-10T11:59:23.203",
    "OutTime": "2016-11-10T11:59:23.203",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/4942ff45-4773-41d9-8c1e-e687efb970d6",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "00:00"
  },
  {
    "EmpID": "ce309ff7-b124-45c9-a016-a3249b844c9b",
    "FirstName": "Saugata",
    "LastName": "Ghosh",
    "InTime": "2016-11-10T16:37:31.07",
    "OutTime": "2016-11-10T16:37:31.07",
    "Picture": null,
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/ca1c9178-ec95-450f-b884-862974cc992a",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "00:00"
  },
  _**{
    "EmpID": "33fb50b7-d92c-44c1-b958-139f76bed4de",
    "FirstName": "Moutusi",
    "LastName": "Singh",
    "InTime": "2016-11-11T10:55:56.55",
    "OutTime": "2016-11-11T10:55:56.55",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/4ded993d-d77c-48e9-b002-3726a12abc53",
    "Present": true,
    "Punctual": true,
    "TotalWorked": "00:00"
  }**_,
  {
    "EmpID": "54f2827d-aae0-4489-8218-530098af3c80",
    "FirstName": "Trijit",
    "LastName": "Dey",
    "InTime": "2016-11-11T10:56:32.547",
    "OutTime": "2016-11-11T19:14:54.057",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/14598c68-23d3-407a-94c4-87ceabccf3f7",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "08:18"
  },
  {
    "EmpID": "9ef3626c-665d-4060-8e75-608ed9b1e274",
    "FirstName": "Debasish",
    "LastName": "Banerjee",
    "InTime": "2016-11-11T11:06:10.7",
    "OutTime": "2016-11-11T11:06:10.7",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/9ee487c9-592b-4be3-a384-3660b849dfdd",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "00:00"
  },
  {
    "EmpID": "f085b970-a085-4102-854e-f0e125b1ca07",
    "FirstName": "Sourik",
    "LastName": "Das",
    "InTime": "2016-11-11T11:27:52.847",
    "OutTime": "2016-11-11T19:10:59.03",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/2de91586-9c4b-46cb-9ed3-c4b4220c1385",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "07:43"
  },
  {
    "EmpID": "33fb50b7-d92c-44c1-b958-139f76bed4de",
    "FirstName": "Moutusi",
    "LastName": "Singh",
    "InTime": "2016-11-14T12:00:01.003",
    "OutTime": "2016-11-14T12:00:01.003",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/bff073c9-ca4d-4c1e-af39-bcd439abd0ad",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "00:00"
  },
  {
    "EmpID": "54f2827d-aae0-4489-8218-530098af3c80",
    "FirstName": "Trijit",
    "LastName": "Dey",
    "InTime": "2016-11-14T11:13:32.227",
    "OutTime": "2016-11-14T11:13:32.227",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/cadcff8b-fe07-44a9-a6f0-455197bc5e23",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "00:00"
  },
  {
    "EmpID": "9ef3626c-665d-4060-8e75-608ed9b1e274",
    "FirstName": "Debasish",
    "LastName": "Banerjee",
    "InTime": "2016-11-14T11:13:13.097",
    "OutTime": "2016-11-14T11:13:13.097",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/7c86da14-62fc-4d5e-8504-c9d08bd2af85",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "00:00"
  },
  {
    "EmpID": "f085b970-a085-4102-854e-f0e125b1ca07",
    "FirstName": "Sourik",
    "LastName": "Das",
    "InTime": "2016-11-14T11:15:25.937",
    "OutTime": "2016-11-14T11:15:25.937",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/2c40f6fe-798c-4f29-b870-14f0946b03b0",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "00:00"
  },
  {
    "EmpID": "33fb50b7-d92c-44c1-b958-139f76bed4de",
    "FirstName": "Moutusi",
    "LastName": "Singh",
    "InTime": "2016-11-15T11:20:40.937",
    "OutTime": "2016-11-15T19:13:32.687",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/46881a03-05a3-4aaa-b7fa-fabbbe7a5864",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "07:52"
  },
  {
    "EmpID": "54f2827d-aae0-4489-8218-530098af3c80",
    "FirstName": "Trijit",
    "LastName": "Dey",
    "InTime": "2016-11-15T12:18:22.67",
    "OutTime": "2016-11-15T19:11:12.287",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/5c0429be-05a6-4757-90d2-5851138bad83",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "06:52"
  },
  {
    "EmpID": "9ef3626c-665d-4060-8e75-608ed9b1e274",
    "FirstName": "Debasish",
    "LastName": "Banerjee",
    "InTime": "2016-11-15T11:54:02.487",
    "OutTime": "2016-11-15T11:54:02.487",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/d566c234-1982-4101-a92d-bfe8c78f4f8c",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "00:00"
  },
  {
    "EmpID": "f085b970-a085-4102-854e-f0e125b1ca07",
    "FirstName": "Sourik",
    "LastName": "Das",
    "InTime": "2016-11-15T11:03:15.157",
    "OutTime": "2016-11-15T19:10:52.113",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/7bbc2476-8ae9-446a-823b-ade1b0e53e0f",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "08:07"
  },
  {
    "EmpID": "2c851902-5848-4bf2-a52c-7071f24f80ae",
    "FirstName": "Avijit",
    "LastName": "Sarkar",
    "InTime": "2016-11-16T14:09:51.437",
    "OutTime": "2016-11-16T14:09:51.437",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/724c67cf-ff9b-4b97-b090-761909a81815",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "00:00"
  },
  {
    "EmpID": "33fb50b7-d92c-44c1-b958-139f76bed4de",
    "FirstName": "Moutusi",
    "LastName": "Singh",
    "InTime": "2016-11-16T11:14:08.473",
    "OutTime": "2016-11-16T12:23:25.417",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/62512c4b-f6be-4fcd-95a3-a3458cdac71d",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "01:09"
  },
  {
    "EmpID": "54f2827d-aae0-4489-8218-530098af3c80",
    "FirstName": "Trijit",
    "LastName": "Dey",
    "InTime": "2016-11-16T11:31:44.53",
    "OutTime": "2016-11-16T11:31:44.53",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/6f5ad521-5f01-44cc-b17f-b2ec0a07d71d",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "00:00"
  },
  {
    "EmpID": "9ef3626c-665d-4060-8e75-608ed9b1e274",
    "FirstName": "Debasish",
    "LastName": "Banerjee",
    "InTime": "2016-11-16T11:20:27.607",
    "OutTime": "2016-11-16T11:20:27.607",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/781df6c3-517a-4ceb-af2c-fadb9c0667fc",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "00:00"
  },
  {
    "EmpID": "f085b970-a085-4102-854e-f0e125b1ca07",
    "FirstName": "Sourik",
    "LastName": "Das",
    "InTime": "2016-11-16T11:31:38.893",
    "OutTime": "2016-11-16T11:31:38.893",
    "Picture": "",
    "ImageUrl": "https://attendanceimages.blob.core.windows.net/attendance-images1/654b09d4-2471-49b2-9e79-41ce0a1dd2c8",
    "Present": true,
    "Punctual": false,
    "TotalWorked": "00:00"
  }
]

**Comment by krishnandusarkar** [comment]
This is fixed in Staging.
