### ISSUE TITLE
Email already taken - Error Checking process taking  time, loader needed.Signup error message UI issue to be fixed.

### ISSUE THREAD

**Issue by debasishbanerjee** [krishnandusarkar/Regular.li#20]
![image](https://cloud.githubusercontent.com/assets/16253897/12085102/2855637a-b2e2-11e5-8b1f-a29e0fd594fa.png)

**Comment by snowbreeze** [comment]
Implement loader

**Comment by krishnandusarkar** [comment]
Why this has been assigned to me?

I'm already throwing email already taken. What else should I need to do?

**Comment by snowbreeze** [comment]
If I delete a user and then want to add him again. What is to be done?

**Comment by krishnandusarkar** [comment]
I'll delete everything on delete. So you can create user again as usual
normally.

**Comment by snowbreeze** [comment]
Ok go ahead!
