### ISSUE TITLE
User FieldTracking Report Email Post Error(Unauthorize Operation)

### ISSUE THREAD

**Issue by trijitdey** [krishnandusarkar/Regular.li#202]
Request URL: https://regularlystaging.azurewebsites.net/api/FieldTrackingReport?UserID=b223c21a-766b-40aa-ab88-c021196efe45&dateFrom=2016-11-22&dateTo=2016-11-22
Request Method:OPTIONS
Status Code:200 OK
Remote Address:23.101.27.182:443

**Query String**
UserID: b223c21a-766b-40aa-ab88-c021196efe45
dateFrom: 2016-11-22
dateTo: 2016-11-22

User Login :  jogendra2field@grr.la/password12

**Comment by krishnandusarkar** [comment]
This is fixed

![image](https://cloud.githubusercontent.com/assets/3623328/20535400/94a80556-b10a-11e6-9ae4-6774088ac80f.png)
