### ISSUE TITLE
Error in Branch Put in Enterprise

### ISSUE THREAD

**Issue by trijitdey** [krishnandusarkar/Regular.li#203]
User Login - nagma@grr.la/password12

Request URL:https://regularly.azurewebsites.net/api/Companies/7018
Request Method:PUT
Status Code:500 Internal Server Error
Remote Address:23.101.27.182:443

**Token**

authorization:bearer 8Z03iiQI9oOte47DDvqGFZasyJOd7-Z13AsIRSaQzSi4SAlAjGhZyjYJ9F-33mAjftvZ8mHq-e2_I6JfiRY2SuHu6vBpGEdDC-QoyfF_cCum4FqySJI5Gw-Ks7dGSeSKRwJnvo9rouPB4coOZwsi27OZHf8h9oeVAZyr8CiKBS_AG_4mAPHPLyqed5FmsjG9_d9Rks1umn6y5DIJHCqVGy4JQTEQm7YM5gaZFi0d2N0hLKZB3xrKLpXq6k2aPXCYqWJoEWbn3x3LF4SCYeM1nbyNk8yKslJeNcE_xtGWUkIi52mT_3E5A14MLIQMBZIZSwxVnyHDwZfbmsXiJ_C1KBIPRmjdfD36iocnQto6yXnW0gkpSKZaEtWCfQmJchOSb3UStY82MEjnanD6tlLgzJCX1BZbvGr961mWbiL08HuKusY28UB5q6UZmgFC4CWytTxVeXtHx3icbp0O_l4QkQSQSxz31M68h0E3Z6le-zfhU3c2flhbTWF4YiWNqORb69bPf21V6CqZx00LjsHvP7cG8xempnnT_uiKBSzLYBZy12HrZsDxLf65XMCVgxonnVVX-LdOZ-x-5SsAYqLb4hDTkGBtscDerxB8m7GeBRzQABtvyaLUkqjNAS7Kfn28_thaAuuJvwRL9hVUq_TBLu1WxtHvDjBGZ-HPFxiisjJf91-63H4Hviy0YsLaUk0WatnnxBsax_Q4VHfTmhv2Ga9mBOwyk_5_dQP5Q3EpDt21D6CS1DydFRVadgB_pHQvaswSU9iZTb2D2FXOumIYk3cK3eY2RSC8Gb9Rk84wni0P7L4WgKwC5Dcr7eJbk1BMUMhCaYD4d9bknw5WB9tB1DAH6wEWO-l3mgpOLPJ75ovKQqV7KZ7lj1_q8r0y43YS

**Query String** - 

{"CompanyID":"7018","CompanyName":"Delhi Branch","TimeZoneID":"India Standard Time","CompanyAddress":"Cariappa Marg","CompanyCity":"New Delhi","CompanyState":"DL","CompanyCountry":"IN","CompanyZip":"110010","LatLong":"28.5961279,77.15873750000003","Radius":"100","InTime":"10:00:00","FirstTimeSetupDone":true,"RestrictByLocation":true,"RestrictByPicture":true,"AllowWebCheckin":true,"Source":"EnterpriseWeb","ParentCompanyID":7016}`

**Response** - 

{"Message":"An error has occurred.","ExceptionMessage":"Attaching an entity of type 'Avifa.Regularly.Data.Models.Company' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.","ExceptionType":"System.InvalidOperationException","StackTrace":"   at System.Data.Entity.Core.Objects.ObjectContext.VerifyRootForAdd(Boolean doAttach, String entitySetName, IEntityWrapper wrappedEntity, EntityEntry existingEntry, EntitySet& entitySet, Boolean& isNoOperation)\r\n   at System.Data.Entity.Core.Objects.ObjectContext.AttachTo(String entitySetName, Object entity)\r\n   at System.Data.Entity.Internal.Linq.InternalSet`1.<>c__DisplayClassa.<Attach>b__9()\r\n   at System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)\r\n   at System.Data.Entity.Internal.Linq.InternalSet`1.Attach(Object entity)\r\n   at System.Data.Entity.Internal.InternalEntityEntry.set_State(EntityState value)\r\n   at Avifa.Regularly.WebAPI.Controllers.CompaniesController.<PutCompany>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}

**Comment by krishnandusarkar** [comment]
This is working fine.
