### ISSUE TITLE
Error in Super Admin Update

### ISSUE THREAD

**Issue by trijitdey** [krishnandusarkar/Regular.li#204]
User Login - nagma@grr.la/password12

Request URL:https://regularly.azurewebsites.net/api/Account/User?id=71bc1868-8c1e-45dd-aa46-5549689b65aa
Request Method:PUT
Status Code:400 Bad Request
Remote Address:23.101.27.182:443

**Token** - 

bearer 8Z03iiQI9oOte47DDvqGFZasyJOd7-Z13AsIRSaQzSi4SAlAjGhZyjYJ9F-33mAjftvZ8mHq-e2_I6JfiRY2SuHu6vBpGEdDC-QoyfF_cCum4FqySJI5Gw-Ks7dGSeSKRwJnvo9rouPB4coOZwsi27OZHf8h9oeVAZyr8CiKBS_AG_4mAPHPLyqed5FmsjG9_d9Rks1umn6y5DIJHCqVGy4JQTEQm7YM5gaZFi0d2N0hLKZB3xrKLpXq6k2aPXCYqWJoEWbn3x3LF4SCYeM1nbyNk8yKslJeNcE_xtGWUkIi52mT_3E5A14MLIQMBZIZSwxVnyHDwZfbmsXiJ_C1KBIPRmjdfD36iocnQto6yXnW0gkpSKZaEtWCfQmJchOSb3UStY82MEjnanD6tlLgzJCX1BZbvGr961mWbiL08HuKusY28UB5q6UZmgFC4CWytTxVeXtHx3icbp0O_l4QkQSQSxz31M68h0E3Z6le-zfhU3c2flhbTWF4YiWNqORb69bPf21V6CqZx00LjsHvP7cG8xempnnT_uiKBSzLYBZy12HrZsDxLf65XMCVgxonnVVX-LdOZ-x-5SsAYqLb4hDTkGBtscDerxB8m7GeBRzQABtvyaLUkqjNAS7Kfn28_thaAuuJvwRL9hVUq_TBLu1WxtHvDjBGZ-HPFxiisjJf91-63H4Hviy0YsLaUk0WatnnxBsax_Q4VHfTmhv2Ga9mBOwyk_5_dQP5Q3EpDt21D6CS1DydFRVadgB_pHQvaswSU9iZTb2D2FXOumIYk3cK3eY2RSC8Gb9Rk84wni0P7L4WgKwC5Dcr7eJbk1BMUMhCaYD4d9bknw5WB9tB1DAH6wEWO-l3mgpOLPJ75ovKQqV7KZ7lj1_q8r0y43YS

**Form Data** - 
Id=71bc1868-8c1e-45dd-aa46-5549689b65aa&FirstName=Nagma&LastName=&PhoneNumber=%2B917854125635&DateOfBirth=1980-02-06&TimeZoneID=UTC&CustomID=

**Response** - 

{"Message":"Unauthorized Operation"}

**Comment by krishnandusarkar** [comment]
This is fixed.

![image](https://cloud.githubusercontent.com/assets/3623328/20535832/87b0dad8-b10c-11e6-85f5-7ad372aa3eb0.png)
