### ISSUE TITLE
Company Put Error in Enterprise

### ISSUE THREAD

**Issue by trijitdey** [krishnandusarkar/Regular.li#205]
Super Admin Login - geeta@grr.la/password12

Request URL: https://regularlystaging.azurewebsites.net/api/Companies/4112
Request Method: PUT
Status Code: 400 Bad Request
Remote Address: 23.101.27.182:443

**Token** - 

bearer FqetXNy4e4rBJDNGkFs5UDPupuKuLtVSNzFb3v2k3i69lfevur9fGSiREVrqayW-xHl8dkfAEE1HC_jPrQcKoGdWghKtmx6r2vkoR8S-Mq0lse_ih_99f6MTtA94Au9VFE8Ag0rDLuKn7pAPmmnXD2WYFwV9acg8anq0IRuVtw2o1-eBHNo0RcTEVi-szgVZjGzwLXpNGridAXMboGj3xxeEOiQBH_ZF8cHORDd41qkr6rU7TtOenkJlCiAXrCxkk-lyr_aUqoKRnGFFR22oV-_tipx0VunhAeelWRm2t5pBvBG7nE3nNtPMoz2Ra4UzgX0G6xyVfc73kUxF8tzhxDdcGq02KLLmvphllq7XOtuYTB_mf6XT7V-d--4kN7i1CM_L09Y0ZEy1BcWGgBykWBc5f1-CUl3L-4uDQ6jw-SbjT61Lwu39tQ4FCEP-sJ4IX1jYI-CGctEoO6kQIYVkf2rm3px6Bpsu-RkpNDABTQslRH8Z5IbyYZPQ_GvCaoIKJYQB8Ku4WycV1DO9IHXb4Elua2xzD-QOyCntn8nBTtvGczFAhFVPZ4Nbx50tgWdb-AcA9CcnCp78nyBcxUJg873PFHuuCHrIwLznAG-Uh8Lzo8a9BCZdl39il6jFYK4MLxS7nREucbHe1nEVY0FP8jkQeYohJtvMh0BykvXI1gM2ys2O3x2043NSJTbQ5XzRa-qL3W9jQ4dis_qx_-EiCm9vOLZZieBKwOue0O-qe2-6qBbrz81V2s85uYvsYmoVJXoqJVTKwtpvD022lD-hB3K8fM0ppetMKXGTejJsdWvVwc-ELtI7DYGtR1lyYYa1k5W2MOKB1PvKu_G0ykFePtxKkXYsrR994lzbJIWnKsHOd6aLyUvZH1hdfzwtENUQl5JOe1JFsEsAsBrVmlITmA

**Query String** -

{"CompanyID":4112,"CompanyName":"Geeta Comp","CompanyAddress":null,"CompanyCity":null,"CompanyState":null,"CompanyZip":null,"CompanyCountry":null,"CompanyEmail":null,"CompanyPhone":null,"IsWorkFromHomeEnabled":false,"LatLong":null,"Radius":0,"FirstTimeSetupDone":false,"RestrictByLocation":false,"RestrictByPicture":false,"AllowWebCheckin":false,"InTime":"00:00:00","WiFiSSID":null,"TimeZoneID":"India Standard Time","ExpiryDate":"2016-12-23T06:58:52.73","ParentCompanyID":null,"SubscriptionType":1}

**Response** - 

{"Message":"Unauthorized Operation"}

**Comment by moutusi12singh** [comment]
Issue Solved
