### ISSUE TITLE
 Checkin Error

### ISSUE THREAD

**Issue by trijitdey** [krishnandusarkar/Regular.li#206]
User Login - sonu@grr.la/password12

Request URL:https://regularlystaging.azurewebsites.net/api/Attendances
Request Method:POST
Status Code:400 Bad Request

**Request Payload**

Location: ""
Picture: "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCABkAEsDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDGooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP/2Q=="
WiFiSSID: "AVIFA_c0:56:27:d6:06:47"

**Token**

bearer 2WQEE9ZZDwDlic63clV4gPRhqSnpZtuu-VrNjJj0YYJVqtlClT55ex44qI-4S0f-dQTG437cd_UMukS2oBxVfZ0RocjroOZVUqgQof2ugVOe_Q0gPmikCMGDd1zy7U9m9nzauG4RO-ZMbsP6wkmCM5X9coJQwKf71UzhhaoNm3emOgGJz0ayy6kY6r4FvbrTe582SwVefaH3fVhLbkkkUF827Z_-LGhWNYchZn4-xZ662vnRi6v1G4YPsy-x7WpLqiMwyA33EbNB6pFiwmctR6UMs6_kNoQ3Q-YPHTVnbJzUAGPvkl8BpUG4VtgBQfHIjOAieCMiK--z5KvhbP2NaBB7a4ESyt8GqCX4sGtthH1nD6eMbs6RmsH9bfrvn9glUTngzlIcarQtk9lW1KVapusQ1NA5JS3SxNcxu_wDgZRz4NYT95wOgi3eiyUu5zO8GJ74lsxvea8KwcgOsMxpICudPrdhJsqheFKVn2wcxP0vR1aN9bkC8umRY1NY7oZaNwYd1tPWfsfxdT90Hcbi15dD4wvVzlfdghlqRNj6zmgfvPKwQ7AzgHOO1eq3cx9053Z-K3Opqy72N6xpiDgNVRG6G2eQEDOSXvQ3zC3ulQNZ-yGG6ZMVO1qxkrbQXfJjOUgngMicfEQMOPzcb0rleezJaYRlqTKZJjm2RjJR-ajFiTJqI5QUw3n0pzgpYyxjH2IUh0RS1z-As0LaOyGLZiO_PXe6gkEugufwZleUGkG2D30c11qGowFNIpn09DVp2wFaJ0vJ_VtdLdbOIXab4D3MxmMesIDWbdEsbb3SiHGVdE-cH3v_rlrMH0Fv916d-rJD7CHyFY9yQp0udVQirq68CJoejcmqZLzmnS8cOUul0ZNx9Z6t0J-7NCQW087g_OFF2i0qHDaWcKZGXyR4wGmkqOXpoaS1Ytme0hs7mt4

**Response**

{"Message":"The request is invalid.","ModelState":{"attendance.UserID":["The User ID field is required."]}}

**Comment by moutusi12singh** [comment]
Not solved yet

**Comment by krishnandusarkar** [comment]
Fixed
