### ISSUE TITLE
WebCheckin User Ontime Issue

### ISSUE THREAD

**Issue by moutusi12singh** [krishnandusarkar/Regular.li#207]
**Super Admin**:  geeta@grr.la
**Branch Name**:  Kolkata_Lake_Branch
**Admin**:  sonu@grr.la
**Web Checkin User**:  sonu3web@grr.la
**Company Intime**:  2:00 PM
**Problem Summary**
For WebCheckin User Ontime Calculation is not working properly. Webcheckin user is present in 1:49 PM but in Admin Dashboard graph is not shown i.e.- webcheckin user is present in Ontime.

**Steps**
Open App, Login to dashboard as Admin (for Regular.li) 
Login through SuperAdmin (for Enterprise)

**Expected Result**
For webcheckin user Ontime calculation must work properly.

**Actual Result**
Ontime Calculation is not working properly.

**Regular.li**
![screenshot_2016-11-24-12-45-45_com avifa regularli](https://cloud.githubusercontent.com/assets/19668188/20591995/68807e0c-b251-11e6-9a6c-14c197f40894.png)

**Enterprise**
![enterprise](https://cloud.githubusercontent.com/assets/19668188/20592030/934597e4-b251-11e6-993d-04c92ab625f5.png)

**Comment by krishnandusarkar** [comment]
Fixed.
