### ISSUE TITLE
QR Image Issue

### ISSUE THREAD

**Issue by trijitdey** [krishnandusarkar/Regular.li#209]
The QRCode is not an image

  {
    "CompanyID": 4113,
    "Email": "sonu4@grr.la",
    "UserID": "0dce3382-aa55-44de-886c-7eea9c7d07ec",
    "PhoneNumber": "+919856325698",
    "UserName": "sonu4@grr.la",
    "FirstName": "Sonu",
    "LastName": "",
    "Address": null,
    "City": null,
    "State": null,
    "Zip": null,
    "Country": null,
    "IsWorkFromHomeAllowed": false,
    "DateOfBirth": null,
    "DateOfJoining": null,
    "RestrictByLocation": true,
    "RestrictByPicture": true,
    "AllowWebCheckin": true,
    "IsEmailConfirmed": true,
    "RestrictByWiFiSSID": true,
    "FieldTracking": false,
    "TimeZoneID": "India Standard Time",
    "EnableEngagement": false,
    "EnableNotification": false,
    "CustomID": "Hg",
    "UserTypeID": 0,
    "QRCode": "https://attendanceimagesstaging.blob.core.windows.net/attendance-images1/77defec9-4e73-4818-88b5-4a0bd6627e37"
  }

**Comment by krishnandusarkar** [comment]
Fixed
Admin : sonu@grr.la
Password : password12

User : ss@grr.la

```
{
    "CompanyID": 4113,
    "Email": "ss@grr.la",
    "UserID": "bb51edd5-abbd-47b1-9040-f096ed1cd348",
    "PhoneNumber": "sample string 15",
    "UserName": "ss@grr.la",
    "FirstName": "sample string 6",
    "LastName": "sample string 7",
    "Address": "sample string 8",
    "City": "sample string 9",
    "State": "sample string 10",
    "Zip": "sample string 11",
    "Country": "sample string 12",
    "IsWorkFromHomeAllowed": true,
    "DateOfBirth": "2016-11-24T00:00:00",
    "DateOfJoining": "2016-11-24T00:00:00",
    "RestrictByLocation": true,
    "RestrictByPicture": true,
    "AllowWebCheckin": true,
    "IsEmailConfirmed": false,
    "RestrictByWiFiSSID": true,
    "FieldTracking": true,
    "TimeZoneID": "sample string 19",
    "EnableEngagement": true,
    "EnableNotification": true,
    "CustomID": "sample string 22",
    "UserTypeID": 0,
    "QRCode": "https://attendanceimagesstaging.blob.core.windows.net/attendance-images1/27269df4-ce33-4a38-a7f0-febca464d98b"
  }
```
