### ISSUE TITLE
Login failed message shown at console.No proper error message given to enduser

### ISSUE THREAD

**Issue by debasishbanerjee** [krishnandusarkar/Regular.li#21]
![image](https://cloud.githubusercontent.com/assets/16253897/12085139/86cd507a-b2e2-11e5-8bb2-8bd07bbdc70c.png)

**Comment by snowbreeze** [comment]
@trijitdey dump the network response

**Comment by krishnandusarkar** [comment]
@trijitdey Emp is never deleted from the system. So once you delete it's deactivated. But that means user can't sign up again with that same Email ID.

@snowbreeze Do you really have such business that user will register with same email? I don't think this is allowed anywhere in public domain.

Let me know your views. I'll take care the technical things behind.
