### ISSUE TITLE
AttendanceByUser Issue

### ISSUE THREAD

**Issue by trijitdey** [krishnandusarkar/Regular.li#211]
Admin - sonu@grr.la
User - sonu4@grr.la
Password - password12

Request URL:https://regularlystaging.azurewebsites.net/api/AttendanceByUser
Request Method:POST
Status Code:500 Internal Server Error

**Token** -

bearer fLcS3QGzmkQXrF57C-27zrr4oO3KJWZDiYsMS_cJ_MH8cCyRxKITpS8iqc8XjBwtiGKpsaeL44EroOV3KeRuyR9bDVDXPpsHyRurUAQ3htG9ZcMkizUS2Xuglly7OYisxi_IGKmanUo8rODjj8G2fSAKxHNMIV91yXckwjZmEmfWY-LpqK0UtbBZlfO07Hv79FTc6q2uTXZJOz_q12270Wg6RZDdCgnuazLs2TN4J_e8-NbSphCxzCUVeI_ac3GuawGNgkkIB8RNSOvAlKi6QdkHj9o_jzd0F_bOvoNHQpHzaSGe9YDoKehozNylaCUv_Njaklo9aaMHUPdhEGTghLlHzTQRMZM9DWN7o29Mpzh55AR-NiSGEFRkEsUX6fyZyd93kQpTAgDxbX8B7frgZJA8olZpk6SLpFJNO0aYf3Psb0U3xqhwLKNs0slbk5cH3fGWaozN4MHe4tqoFw_OKsZdwXWubLarAoCMDSCZligCWIj34DS6xRS-h9Z7iDGdXisLMEKsd9XcNKlCYc_-4tHjusGOJFP8zM0YBUB4ESd5B_D0Viu6Bvf0ip_Ys2lLdrovUU9dQW3yo9OlkDetAnhbobZZP_NAzdQ-eVuO7WuUhlmUjogHUTx3FUGhJQ-RiaZanC7_1L0fopHkIFVfMzqZb9s87BJWRVWSu4RdA6YqB8EIpFOnQEcJacqJM0wDgGVoFcKQQhMX5cA3cKjM4LpMt9-wm0gTh8p7snTvHSmhbenJm6dvlrG1p8dqy0QZ2ztDWoj1Aecwtc3eLXeEVH1Eu3JgzdCsygwA3NhA4V1Tya-fq_MVRiOpNDc4J3qP5FldBY105rHxgIROBo8dFAorv546BhEDsZrI3moIwnEprb6wrr44DQ9gHPWzNmeO8g6fsfW35xVix03CYc_F62a3x_76olhfYexvl9MZpxg

**Request Payload** - 

Location: "22.5110332,88.3504571"
Picture: "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCABkAEsDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCEU4UgIqeGLcckcU72JSuEUJc+gq0qBBgClAwMUtQ2Wo2EpkiK4wRTjSE0XHYz5EKMRTCKsXHLCoDWi1Rk1ZjKTFPxSYoETwx7256VeGFGKijXYMVJurJu5slYXNGaYTSZoGPNMJ4oLVE78UARStuaozTjSVqlYwbuxtJTsUmKBGnxTWHpRupN1ZHQMzikLU5sGoX4FAA74FQb9xpkkmTgURjmrijOb6ElLRilxVmYmKSn4pMUAP8ANpfMql5lKJKxOgueZUcj/Kag8ymu27imkJsFG5s1OFxtP4UyJcmrLriLPpzWqMGxlFLRQAUYpaPxoAzM0oNMpazNx4NPQZNRZxUsRpoiRbiXFTHlCPaoEcYqUOKszGKcqKWo1OMj0NOzQA4GlzTc0mfegDMpc0lIag1Amno+KjooAsianCf3qrSg07k2LIk+Y+9PElVVNPBp3FYsh6dvqAGnbqBWKdJRRUmgUUUUAFLRRQAop4oopiY8UtFFMk//2Q=="
UserID: "0dce3382-aa55-44de-886c-7eea9c7d07ec"
WiFiSSID: "AVIFA-FASTLANE_1c:5f:2b:2e:c1:40"

**Response** - 

{"Message":"An error has occurred.","ExceptionMessage":"UrlHelper.Link must not return null.","ExceptionType":"System.InvalidOperationException","StackTrace":"   at System.Web.Http.Results.CreatedAtRouteNegotiatedContentResult`1.Execute()\r\n   at System.Web.Http.Results.CreatedAtRouteNegotiatedContentResult`1.ExecuteAsync(CancellationToken cancellationToken)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}

**Comment by krishnandusarkar** [comment]
Fixed

**Request :**
```
{
  "UserID": "bb51edd5-abbd-47b1-9040-f096ed1cd348",
  "Location": "22.5110332,88.3504571",
"Picture": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCABkAEsDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCEU4UgIqeGLcckcU72JSuEUJc+gq0qBBgClAwMUtQ2Wo2EpkiK4wRTjSE0XHYz5EKMRTCKsXHLCoDWi1Rk1ZjKTFPxSYoETwx7256VeGFGKijXYMVJurJu5slYXNGaYTSZoGPNMJ4oLVE78UARStuaozTjSVqlYwbuxtJTsUmKBGnxTWHpRupN1ZHQMzikLU5sGoX4FAA74FQb9xpkkmTgURjmrijOb6ElLRilxVmYmKSn4pMUAP8ANpfMql5lKJKxOgueZUcj/Kag8ymu27imkJsFG5s1OFxtP4UyJcmrLriLPpzWqMGxlFLRQAUYpaPxoAzM0oNMpazNx4NPQZNRZxUsRpoiRbiXFTHlCPaoEcYqUOKszGKcqKWo1OMj0NOzQA4GlzTc0mfegDMpc0lIag1Amno+KjooAsianCf3qrSg07k2LIk+Y+9PElVVNPBp3FYsh6dvqAGnbqBWKdJRRUmgUUUUAFLRRQAop4oopiY8UtFFMk//2Q==",
"WiFiSSID": "AVIFA-FASTLANE_1c:5f:2b:2e:c1:40"
}
```

**Response :**

```
{
  "AttendanceID": 7831,
  "UserID": "bb51edd5-abbd-47b1-9040-f096ed1cd348",
  "IsWorkFromHome": false,
  "AttendanceDateTime": "2016-11-24T21:15:24.722066",
  "Location": "22.5110332,88.3504571",
  "Picture": "",
  "WiFiSSID": "AVIFA-FASTLANE_1c:5f:2b:2e:c1:40",
  "Punctual": false,
  "Note": null,
  "ImageUrl": "https://attendanceimagesstaging.blob.core.windows.net/attendance-images1/5f902c5d-42d0-435f-b153-33722ecbe47b"
}
```
