### ISSUE TITLE
In API response need In or Out Response

### ISSUE THREAD

**Issue by trijitdey** [krishnandusarkar/Regular.li#215]
/api/Account/EmployeesByCompany

/api/Account/AdminsByCompany

In these API need's a response He/She is In or Out.

**Comment by krishnandusarkar** [comment]
![image](https://cloud.githubusercontent.com/assets/3623328/20840950/fe63bd44-b8d7-11e6-9b8b-a274f90b8e59.png)


![image](https://cloud.githubusercontent.com/assets/3623328/20840959/0bfcdaee-b8d8-11e6-94cf-160c7451765d.png)
