### ISSUE TITLE
Error in Attendance Post

### ISSUE THREAD

**Issue by trijitdey** [krishnandusarkar/Regular.li#219]
Admin User - amit123@grr.la/password12 

*********[ Expiry date of company : 2017-12-07 ]********

User -  pupu3@grr.la/password12

Request URL:https://regularlystaging.azurewebsites.net/api/Attendances
Request Method:POST
Status Code:400 Bad Request

Request Payload - 

Picture: ""
UserID: "21ca4432-fcf3-4920-8712-98127891fe77"
WiFiSSID: ""

Response -

Message: "Your account is expired. Please check with your Administrator."

**Comment by moutusi12singh** [comment]
fixed.
