### ISSUE TITLE
Forget password giving 400 (Bad Request) at console 

### ISSUE THREAD

**Issue by debasishbanerjee** [krishnandusarkar/Regular.li#22]
![image](https://cloud.githubusercontent.com/assets/16253897/12085169/f12cab00-b2e2-11e5-9f0d-f6b7719e34d9.png)

**Comment by snowbreeze** [comment]
@trijitdey post all network info

**Comment by trijitdey** [comment]
Resolved with correct email address.

**Comment by krishnandusarkar** [comment]
Why has this been reopened? Is there anything I need to do from my end?

BTW, for your info, Bad Request can mean...
1. Either the user doesn't exists in the system
2. Or the user doesn't have confirmed email address.
