### ISSUE TITLE
Holiday Is Registered Successfully but Showing Email,First Name,Last Name field is required.

### ISSUE THREAD

**Issue by trijitdey** [krishnandusarkar/Regular.li#28]
![untitled2](https://cloud.githubusercontent.com/assets/10113540/12085607/b109114e-b2e7-11e5-8b3b-0362cb1b34f3.png)

**Comment by snowbreeze** [comment]
@trijitdey post network
You are getting the alert because it has reached .done at the same time some other query has created that msg.
