### ISSUE TITLE
Creation of LeaveType

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/Regular.li#3]
1. The titles should say "Leave Type". As we are creating types of Leave.
2. After successful creating of Leave Type, the form should be cleared for next entry. Else user needs to clear up the form and in worse case user can press submit multiple times which will create same Leave Type multiple times.

![screenshot_2015-11-30-22-31-15](https://cloud.githubusercontent.com/assets/3623328/11478680/7b6da822-97b4-11e5-82a6-7b9ddf9af15e.png)

**Comment by trijitdey** [comment]
solved.

**Comment by krishnandusarkar** [comment]
Retested and working fine.
