### ISSUE TITLE
Mandatory workfromhome flag in company

### ISSUE THREAD

**Issue by snowbreeze** [krishnandusarkar/Regular.li#39]

**Comment by krishnandusarkar** [comment]
It's not mandatory in both Company and Attendance. Reopen if issue persists.

![company](https://cloud.githubusercontent.com/assets/3623328/12174236/891cd41c-b581-11e5-9aa8-6f34b021f0d0.jpg)
![attendance](https://cloud.githubusercontent.com/assets/3623328/12174238/8921c54e-b581-11e5-8faf-bfa49d7ec206.jpg)
