### ISSUE TITLE
Creation of Holiday

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/Regular.li#4]
1. Holiday Date is not marked as * i.e. Mandatory.
2. If user tried to create Holiday without entering Holiday Date, though the system doesn't does anything, but proper error message should be shown.

![screenshot_2015-11-30-22-43-20](https://cloud.githubusercontent.com/assets/3623328/11478731/af0640f4-97b4-11e5-9a37-bc537b6e9a51.png)

**Comment by trijitdey** [comment]
Solved the issue.

**Comment by krishnandusarkar** [comment]
Retested and working fine.
