### ISSUE TITLE
Export to email

### ISSUE THREAD

**Issue by snowbreeze** [krishnandusarkar/Regular.li#40]
From mobile we cant send file, because we cant generate file.
we can send file contents.

**Comment by krishnandusarkar** [comment]
@trijitdey Let me know the JSON format that you'll be sending once you reach home.

**Comment by snowbreeze** [comment]
If trijit is delaying you can go ahead and define a format.
target is to send out a csv to client.
trijit can send you the exact file contents.

**Comment by krishnandusarkar** [comment]
That wont work. I need the exact format (i.e. columns)

**Comment by krishnandusarkar** [comment]
Done. Reopen if issue persists.
