### ISSUE TITLE
Starting Cards

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/Regular.li#59]
1. Starting cards are appearing everytime I open the app. Generally starting cards are shown only on first run.

**Comment by krishnandusarkar** [comment]
2. Open the app -> starting cards are being shown -> navigate through them and click end tutorial -> we are in login page -> click back button twice and the app will close down. Again open the app from Menu or Resume the app using recent apps button (right most button on home screen) -> the app again falls back to starting cards. It should stay in login page.

**Comment by snowbreeze** [comment]
f
