### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/Regular.li#60]
1. Can we make a better UI of login page? Looks clumsy as of now.

2. Terms & Privacy links are not working.

3. When I click Password Help, it navigates to Reset Password page which is absolutely fine but if I click back button on Reset Password page it goes back to Starting Cards. It should navigate back to Login Screen.

**Comment by trijitdey** [comment]
http://codepen.io/anon/pen/EPXVBy

**Comment by krishnandusarkar** [comment]
Looks nice. Atleast dont use that background image, it's too heavy such
that it attracts eye more than the login controls.

Thanks and Regards,
Krishnandu Sarkar
