### ISSUE TITLE
Data Headers On Cards

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/Regular.li#65]
This really doesn't makes sense what the data is about. Can we use glyphicons along with headers to denote what the data is about?

![screenshot_20160110-111910](https://cloud.githubusercontent.com/assets/3623328/12220206/d5039916-b78d-11e5-9cbc-2d9f9b1bf107.png)

**Comment by snowbreeze** [comment]
@trijitdey data-title to td
