### ISSUE TITLE
Materialistic Time & Input

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/Regular.li#67]
Can we change Time & Date inputs to materialistic one? Like Clock for Time?

![screenshot_20160110-114323](https://cloud.githubusercontent.com/assets/3623328/12220248/479b2dca-b790-11e5-8868-afacf257885d.png)

**Comment by snowbreeze** [comment]
@krishnandusarkar not possible at moment. will require complete change.
