### ISSUE TITLE
How do I point a location on Map?

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/Regular.li#68]
How do I point a location on Map? Currently tapping on map is not creating a pointer.

Also can we enable the map center button? Like Uber and Ola and other maps based apps where, when you click the button it centers the map to that location and create a pointer on that location.

![screenshot_20160110-114412](https://cloud.githubusercontent.com/assets/3623328/12220250/68396222-b790-11e5-9f8b-6871901defcf.png)

**Comment by snowbreeze** [comment]
Add on click listner to the map. 
On click setLocation(  ) something something
