### ISSUE TITLE
Validation Message

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/Regular.li#69]
Please check the example below. Why are we showing "A Value is required"? The Holiday Reason field is required should suffice. Can we make the card red for better visibility and denoting error?

![screenshot_20160110-114510](https://cloud.githubusercontent.com/assets/3623328/12220251/a6e32e04-b790-11e5-8f62-75131b542137.png)

**Comment by snowbreeze** [comment]
@krishnandusarkar  Messages are server bound. Please correct message in server side.

@trijitdey  verify the same

**Comment by krishnandusarkar** [comment]
It's not from my end. I think @trijitdey is prefixing the text.

![untitled](https://cloud.githubusercontent.com/assets/3623328/12237914/3e452d6c-b8a7-11e5-9422-c5052b76fd2f.jpg)

**Comment by snowbreeze** [comment]
Bad trijit
