### ISSUE TITLE
Time Incorrect

### ISSUE THREAD

**Issue by snowbreeze** [krishnandusarkar/Regular.li#8]
All timings must be in local time of the user

**Comment by trijitdey** [comment]
Solved.

**Comment by krishnandusarkar** [comment]
I just did a check in and still it's wrong.

![screenshot_2015-12-02-23-19-32](https://cloud.githubusercontent.com/assets/3623328/11539082/4c20d3f8-994b-11e5-8ed6-3525e564ce56.png)

**Comment by snowbreeze** [comment]
Still wrong.

**Comment by trijitdey** [comment]
[image: Inline image 1]


I dont know what kind of prob it is.I m getting exact local time.
