### ISSUE TITLE
Sidebar Menu Issue in APP

### ISSUE THREAD

**Issue by trijitdey** [krishnandusarkar/Regular.li#84]

**Comment by snowbreeze** [comment]
what is the issue?

**Comment by trijitdey** [comment]
![screenshot_2016-01-17-23-47-44](https://cloud.githubusercontent.com/assets/10113540/12379030/05fd3344-bd77-11e5-939b-c4d475a37e9e.png)

**Comment by snowbreeze** [comment]
How to reproduce this. I cant reporduce in my phone.
